# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 625fce128232ebe2e36d0cd253ff3db96057af7450a7b0ac7f1edb051d62da8a6fadf00c7048b188b4e545a49171999eaf2fb0faede5bd1acef35a82cc6b1bdd

test:
  secret_key_base: 6e7cc3d674b7f014abc1f7ac6f47599e4bfc1b31bdbf5cda488dc014eaa8ccd8190128cc7c94b212d7abac4c7e1ba8fd4661759ae1920527bdd9d8fb753853b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
